---
title: "Real World Data from Blythe's Apple Watch"
author: "Blythe Adamson"
output:   
  html_document:
    theme: yeti
    highlight: tango
    toc: true
    toc_float: true
---

__Date generated:__ `r format(Sys.time(), '%B %d, %Y')` <br>
__Generated by:__ `r Sys.info()[8]` <br>
__Code review:__ Nope! <br>
__Analysis Plan:__ nada


```{r markdown setup, include = FALSE}
knitr::opts_chunk$set(cache = FALSE, dev = 'png', echo = FALSE, warning = FALSE, message = FALSE, 
                      results = 'asis')
knitr::opts_knit$set(width = 75)

library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(stringr)
library(tidyr)
library(XML)
```


```{r bring in the data}
xml <- xmlParse('/Users/badamson/Documents/apple_watch_data/export.xml')

ecg <- ('/Users/badamson/Documents/apple_watch_data/export.xml')
```

# Objective

This is an exploratory analysis where I aim to play with my watch data. 

```{r}
df_record <-   XML:::xmlAttrsToDataFrame(xml["//Record"])

df_activity <- XML:::xmlAttrsToDataFrame(xml["//ActivitySummary"])

df_workout <-  XML:::xmlAttrsToDataFrame(xml["//Workout"])

df_location <- XML:::xmlAttrsToDataFrame(xml["//Location"]) %>% 
  mutate(latitude = as.numeric(as.character(latitude)),
         longitude = as.numeric(as.character(longitude)))
```

```{r}
df <- df_record %>%
  mutate(device = gsub(".*(name:)|,.*", "",device),
         value = as.numeric(as.character(value)),
         endDate = ymd_hms(endDate,tz="America/New_York"),
         date = date(endDate),
         year = year(endDate),
         month = month(endDate),
         day = day(endDate),
         yday = yday(endDate),
         wday = wday(endDate),
         hour = hour(endDate),
         minute = minute(endDate),
         type = str_remove(type, "HKQuantityTypeIdentifier")
         )
```
# Results

```{r}
df %>%
  filter(type == 'StepCount') %>% 
  group_by(date,wday,hour) %>% 
  summarize(steps=sum(value)) %>% 
  group_by(hour,wday) %>% 
  summarize(steps=sum(steps)) %>% 
  arrange(desc(steps)) %>%

  ggplot(aes(x=hour, y=wday,  fill=steps)) + 
    geom_tile(col = 'grey40') + 
    scale_fill_continuous(labels = scales::comma, low = 'grey95', high = '#008FD5', guide = guide_colourbar(direction = "vertical")) +
    theme(panel.grid.major = element_blank()) +
    scale_x_continuous(
      breaks = c(0, 6, 12, 18),
      label = c("Midnight", "6 AM", "Midday", "6 PM")
    ) +
    scale_y_reverse(
      breaks = c(1,2,3,4,5,6,7),
      label = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
    ) +
    labs(title = "Weekly Step Count Heatmap") +
    coord_equal()
```

<br>

```{r goals completion}
#Some data clean up  and renaming here
df_activity_tidy <- df_activity %>% 
  select(-activeEnergyBurnedUnit) %>% 
  mutate_all(as.character) %>% 
  mutate(date = as.Date(dateComponents)) %>% 
  filter(date >= "2018-11-13") %>% 
  select(-dateComponents) %>% 
  mutate_if(is.character, as.numeric) %>% 
  rename(move = activeEnergyBurned,
         exercise = appleExerciseTime,
         stand = appleStandHours,
         move_goal = activeEnergyBurnedGoal,
         exercise_goal = appleExerciseTimeGoal,
         stand_goal = appleStandHoursGoal) %>% 
  #Now, create 2 new metrics: percent of goal and a "Yes/No" flag.
  mutate(move_pct = move/move_goal,
         exercise_pct = exercise/exercise_goal,
         stand_pct = stand/stand_goal,
         move_bool = if_else(move_pct < 1, FALSE, TRUE),
         exercise_bool = if_else(exercise_pct < 1, FALSE, TRUE),
         stand_bool = if_else(stand_pct < 1, FALSE, TRUE))

df_activity_tall_value <- df_activity_tidy %>% 
  select(date, Move = move, Exercise = exercise, Stand = stand) %>% 
  gather(category, value, -date)

df_activity_tall_pct <- df_activity_tidy %>% 
  select(date, Move = move_pct, Exercise = exercise_pct, Stand = stand_pct) %>% 
  gather(category, pct, -date)

df_activity_tall_bool <- df_activity_tidy %>% 
  select(date, Move = move_bool, Exercise = exercise_bool, Stand = stand_bool) %>% 
  gather(category, boolean, -date)
  
df_activity_tall <- df_activity_tall_value %>% 
  left_join(df_activity_tall_pct, by = c("date", "category")) %>% 
  left_join(df_activity_tall_bool, by = c("date", "category")) %>% 
  mutate(category = factor(category, levels = c("Move", "Exercise", "Stand")),
         month = ymd(paste(year(date), month(date), 1, sep = "-")),
         week = date - wday(date) + 1,
         wday = wday(date),
         day = day(date))

df_activity_tall %>% 
  ggplot(aes(x = wday, y = week, fill = boolean)) +
    geom_tile(col = "grey30", na.rm = FALSE) +
    theme(panel.grid.major = element_blank()) +
    scale_fill_manual(values = c("grey80", "#1a9641")) +
    facet_wrap(~ category) +
    coord_fixed(ratio = 0.15) +
    guides(fill=FALSE) +
    labs(title = "Apple Watch goals completion") +
    theme(axis.text.x = element_blank())
```

<br>

```{r streak count}
df_activity_streak <- df_activity_tall_bool %>% 
  mutate(category = factor(category, levels = c("Move", "Exercise", "Stand"))) %>% 
  arrange(category, date) %>% 
  group_by(category, 
           x = cumsum(c(TRUE, diff(boolean) %in% c(-1))),
           y = cumsum(c(TRUE, diff(boolean) %in% c(-1,1)))) %>% 
  mutate(streak = if_else(boolean == FALSE, 0L, row_number())) %>% 
  ungroup() 


ggplot(df_activity_streak, aes(x = date, y = streak, group = x, col = category)) +
  geom_line() +
  facet_grid(category~.) +
  guides(fill=FALSE) +
  labs(title = "Streak Count")
```

<br>

```{r}
ggplot(df %>% 
  filter(type == "HeartRate"), aes(value)) +
  geom_histogram() + 
  labs(x = "Heart Rate")
```

### References
[Taras Kaduk tutorial](https://taraskaduk.com/2019/03/23/apple-health/).